### ISSUE TITLE
'my_transforms' is not defined

### ISSUE THREAD

**Issue by reborm** [SunnerLi/waiting-for-you-generator#1]
Hi, thank for your share, I found this problem in my test. The 'my_transforms' is a file or writing error

**Comment by SunnerLi** [comment]
Hi @reborm ,
thanks for your remind.
I'm sorry that I fix it too late.
To this problem,
I fix the 'my_transforms' as the 'sunnertransforms'.
You can check the detail in the `visualize.py`. 


In fact,
I also have another experiment which use another dataset.
Moreover, the second experiment can achieve higher performance.
You can also check the detail from my article.


If you have any problem with this issue,
welcome to open this issue again!

**Comment by reborm** [comment]
@SunnerLi  Thank you! I really want to read your article. Could you please let me read it?
